# ğŸŒ¡ï¸ DocumentaÃ§Ã£o do Projeto de CalibraÃ§Ã£o DS18B20

site_name: Projeto de CalibraÃ§Ã£o do Sensor DS18B20
site_description: DocumentaÃ§Ã£o oficial do projeto de calibraÃ§Ã£o e compensaÃ§Ã£o do sensor DS18B20 usando Arduino
site_author: Sofia VitÃ³ria Bispo da Silva & Juliana Bispo
repo_url: https://github.com/Sofiavictoria/Projeto-Final-DS18B20-UnB.git

# Tema
theme:
  name: material
  language: pt-BR
  font:
    text: "Poppins"
    code: "Fira Code"
  palette:
    - scheme: default
      primary: '#003366'   # Azul UnB
      accent: '#0A6A3B'    # Verde UnB
      toggle:
        icon: material/weather-night
        name: Modo escuro
    - scheme: slate
      primary: '#0A6A3B'
      accent: '#003366'
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link

# Menu da documentaÃ§Ã£o
nav:
  - InÃ­cio: index.md
  - Sobre o Projeto: sobre.md
  - Hardware: hardware.md
  - Firmware : firmware.md
  - CalibraÃ§Ã£o: calibracao.md
  - Resultados: resultados.md
  - Equipe: autores.md


# ExtensÃµes Markdown
markdown_extensions:
  - admonition
  - tables
  - footnotes
  - def_list
  - abbr
  - attr_list
  - meta
  
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.tasklist
  - toc:
      permalink: true
      
  # ğŸ’¡ ESSENCIAL PARA RENDERIZAR EQUAÃ‡Ã•ES
  - pymdownx.arithmatex:
      generic: true

# Plugins
plugins:
  - search

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: >
   Â© 2025 â€” Universidade de BrasÃ­lia (UnB).  
    Projeto desenvolvido para a disciplina InstrumentaÃ§Ã£o EletrÃ´nica para Engenharia.  
  
